# Generated by Django 3.2.4 on 2022-02-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0006_alter_blog_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
