# Generated by Django 3.2.4 on 2022-02-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0007_auto_20220205_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoria',
        ),
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appBlog.categorias'),
        ),
    ]
